# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eea13a70ef9550c983dcd873aca504d4"
name = "my-new-app"
handle = "my-new-app-1050"
application_url = "https://agency-blake-portsmouth-buck.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nick-drishinski-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://agency-blake-portsmouth-buck.trycloudflare.com/auth/callback",
  "https://agency-blake-portsmouth-buck.trycloudflare.com/auth/shopify/callback",
  "https://agency-blake-portsmouth-buck.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
